image:
  file: .gitpod.Dockerfile

tasks:
- name: Start Couchbase
  command:  ./startcb.sh && gp sync-done startcb
- name: Log use
  command: curl -s 'https://da-demo-images.s3.amazonaws.com/runItNow_outline.png?couchbase-example=nextjs-quickstart-repo&source=gitpod' > /dev/null
- name: Start app
  init: npm install && gp sync-done deps
  command: gp sync-await deps && gp sync-await startcb && npm run init-db:default && while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' -u Administrator:password localhost:8091/pools/default/buckets/user_profile)" != "200" ]]; do sleep 5; echo "hello"; done && npm run dev:default


# TODO: try waiting on startcb.sh
-
#- name: Install Dependencies
#  init: >
#    npm install &&
#    gp sync-done dependencies
#  command: echo "done install deps"
#- name: Init Db
#  init: gp sync-await dependencies
#  command: >
#    npm run init-db:default &&
#    gp sync-done db-init
#- name: Start app
#  init: echo "Awaiting Dependencies and Database Initiialization" && gp sync-await dependencies && gp sync-await db-init
#  command: while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' -u Administrator:password localhost:8091/pools/default/buckets/user_profile)" != "200" ]]; do sleep 5; echo "hello"; done && npm run dev:default


# TODO: next lets try combining npm install and init db steps again
#- name: Start app
#  init: npm install && npm run init-db:default && npm run test
#  command: while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' -u Administrator:password localhost:8091/pools/default/buckets/user_profile)" != "200" ]]; do sleep 5; done && npm run dev:default

ports:
- port: 3000
  onOpen: open-preview
- port: 8091
  onOpen: open-browser
- port: 8092-10000
  onOpen: ignore
- port: 4369
  onOpen: ignore

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    addCheck: true
